#version: "3"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command:
      - gunicorn
      - musicTrainee.wsgi:application
      - --bind
      - 0.0.0.0:8001
    ports:
      - "8000:8001"
    restart: always
    env_file:
      - .env
    logging:
#      driver: "json-file"
#      options:
#        max-file: "10"
#        max-size: "200k"
        driver: loki
        options:
          loki-url: http://localhost:3100/loki/api/v1/push
#          Не работает, контейнер виснет при попытке остановки, потому что внутри контейнера нет соединения
#          loki-url: http://host.docker.internal:3100/loki/api/v1/push
    volumes:
      - ./musicTrainee/database:/app/database
      - ./musicTrainee/web/static:/app/web/static
      - ./musicTrainee/web/media:/app/web/media

  nginx:
    container_name: NGINX
    build: ./nginx
    volumes:
      - ./musicTrainee/web/static:/app/web/static
      - ./musicTrainee/web/media:/app/web/media
    ports:
      - "8001:80"
    depends_on:
      - app

    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push

  grafana:
    image: grafana/grafana:9.5.2
    environment:
      - GR_AUTH_ANONYMOUS_ENABLE=true
      - GR_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3000:3000"

  loki:
    image: grafana/loki:3.1.1
    ports:
      - "3100:3100"

