version: "3.9"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command:
      - gunicorn
      - musicTrainee.wsgi:application
      - --bind
      - 0.0.0.0:8001
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    volumes:
      - ./musicTrainee/database:/app/database

  nginx:
    container_name: NGINX
    build: ./nginx
    volumes:
      - ./musicTrainee/web/static:/app/web/static
      - ./musicTrainee/web/media:/app/web/media
    ports:
      - "8001:80"
    depends_on:
      - app
