# Generated by Django 5.0.3 on 2024-05-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_task_file_remove_task_user_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='target_description',
            field=models.CharField(default='Targets course', max_length=500),
            preserve_default=False,
        ),
    ]
