# Generated by Django 5.0.3 on 2024-04-02 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_advuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvUser',
        ),
    ]
