# Generated by Django 5.0.3 on 2024-04-03 15:06

import catalog.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_file_image_text_video_module_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='content',
            old_name='owner',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='owner',
            new_name='course',
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=catalog.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=catalog.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
