# Generated by Django 5.0.3 on 2024-06-16 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_content_module_alter_content_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('task_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='catalog.tasksubmission')),
            ],
        ),
    ]
