# Generated by Django 5.0.3 on 2024-06-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_taskreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskreview',
            name='is_correct',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
