# Generated by Django 5.0.3 on 2024-04-07 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_rename_create_date_course_created_course_creator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='owner',
            field=models.ManyToManyField(blank=True, related_name='courses_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
