# Generated by Django 5.0.3 on 2024-04-07 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_course_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='file',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='url',
            new_name='content',
        ),
    ]
