# Generated by Django 5.0.3 on 2024-07-08 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_commentcontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentcontent',
            old_name='autor',
            new_name='author',
        ),
    ]
