# Generated by Django 5.0.3 on 2024-04-07 13:01

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_rename_file_file_content_rename_file_image_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField(max_length=3000, verbose_name='text_question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('file', models.FileField(blank=True, upload_to=catalog.models.course_tasks_directory_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='file',
            old_name='content',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='content',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='content',
            new_name='url',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.question')),
            ],
        ),
    ]
