name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Chechout the code
        uses: actions/checkout@v3
  
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no root@80.90.187.60 << 'EOF'
            cd /root/projects/MT-Server
            git pull origin main
            docker compose down
            docker compose build
            docker compose up -d
          EOF
